---
jira:
  host: 'https://jira.com'
  username: user@widget.com
  api_key: 123abc
  daily_tasks:
    - name: Infra Standup
      issue_key: KEY-99
      time: 15m
  bucket_tasks:
    - name: Done work
      issue_key: KEY-10
      weight: 5
    - name: Not done work
      issue_key: KEY-20
      weight: 1
