Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Security/YAMLLoad:
  Exclude:
    - 'lib/config.rb'
    - 'lib/gojira/config.rb'

Style/GuardClause:
  Exclude:
    - 'lib/config.rb'
    - 'lib/gojira/config.rb'

Style/SymbolProc:
  Exclude:
    - 'lib/jira_bucket_tasks.rb'
    - 'lib/gojira/jira_bucket_tasks.rb'

Style/RescueStandardError:
  Exclude:
    - 'lib/gojira/config.rb'