Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Security/YAMLLoad:
  Exclude:
    - 'lib/config.rb'

Style/GuardClause:
  Exclude:
    - 'lib/config.rb'

# Had issues with running code as suggested in compiler
Style/SymbolProc:
  Exclude:
    - 'lib/jira_bucket_tasks.rb'
